#!/bin/bash
if [[ -z "$1" ]]; then
    cd ..
elif [[ "$1" =~ ^[0-9]+$ ]]; then
    local depth=""
    for ((i=0; i<$1; i++)); do depth="../$depth"; done
    cd "$depth"
else
    # hell i forgot after writing this
    local target="$1"
    local current_dir=$(pwd)
    local destination="${current_dir%\/$target*}/$target"
    if [[ -d "$destination" ]]; then
        cd "$destination"
    else
        echo "target directory '$target' not found in current tree path."
    fi
fi
