#!/bin/bash
if [[ -f $1 ]]; then
    echo -e "\e[1;36m󰛖 extracting archive package...\e[0m"
    case $1 in
        *.tar.bz2)   tar xjf "$1"     ;;
        *.tar.gz)    tar xzf "$1"     ;;
        *.bz2)       bunzip2 "$1"     ;;
        *.rar)       unrar x "$1"     ;;
        *.gz)        gunzip "$1"      ;;
        *.tar)       tar xf "$1"      ;;
        *.tbz2)      tar xjf "$1"     ;;
        *.tgz)       tar xzf "$1"     ;;
        *.zip)       unzip "$1"       ;;
        *.Z)         uncompress "$1"  ;;
        *.7z)        7z x "$1"        ;;
        *.tar.xz)    tar xf "$1"      ;;
        *)           echo -e "\e[1;31m󰅚 '$1' cannot be extracted via extract module\e[0m" ;;
    esac
else
    echo -e "\e[1;31m󰅚 '$1' is not a valid file\e[0m"
fi
